### ISSUE TITLE
Not picking up to use yarn

### ISSUE THREAD

**Issue by robcalcroft** [cloudfoundry/nodejs-buildpack#147]
What conditions do I need for it to use yarn? It has a yarn.lock file and I've specified `yarn: "*"` in the package.json but it still is using npm for some reason?

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?
v1.5.24

If you were attempting to accomplish a task, what was it you were attempting to do? 
Use yarn to install dependencies

What did you expect to happen?
Should use yarn to install deps

What was the actual behavior?
Used npm

Can you provide a sample app?
No

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction
 
```yaml
---
applications:
  - name: my-app
    memory: 1G
    buildpack: sdk-for-nodejs_v3_19-20180314-1533
    env:
      NPM_CONFIG_REGISTRY: http://registry.redacted.com
      NPM_CONFIG_PRODUCTION: false
      NPM_CONFIG_IGNORE_SCRIPTS: true
```
