### ISSUE TITLE
Can't change context for git operations

### ISSUE THREAD

**Issue by Mueslint** [cloudfoundry/nodejs-buildpack#149]
Hello!  
I hope I'm not on the wrong sub-git...

#### What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "Bluemix",
   "build": "270030",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.ng.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.ng.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.92.0",
   "app_ssh_endpoint": "ssh.ng.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.ng.bluemix.net:443"
}
cf version 6.37.0+a40009753.2018-05-25
```

#### What version of the buildpack you are using?
latest as I install from github.com/cloudfoundry/nodejs-buildpack.git 

#### If you were attempting to accomplish a task, what was it you were attempting to do?
I'm just trying to push but my team use private repositories on github Enterprise hence cf building agent fails`npm install` as it tries login/password connection (refused) while it should use a Git token...

#### What did you expect to happen?
That it use the token I defined with set-env...

#### What was the actual behavior?
Childish behavior: it sticks to login/password credentials so github throws `you should use git token or ssh key instead`

#### Can you provide a sample app?
I can't as it is company code but you'll catch the point as it is independant of the app content, imo you can try with:
- a basic hello-world node.js app
- you use a private repository, declared like this: `git+https://github.com/someone/awesome-private-pkg.git` (we can't use npm publish etc...)
- the error will be thrown while cf tries to npm install the private repository with login/password credentials

This is my  error logs:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.ibm.com/CognitiveAssetFactory/kpb-api-pkg
npm ERR! 
npm ERR! remote: Password authentication is not available for Git operations.
npm ERR! remote: You must use a personal access token or SSH key.
npm ERR! remote: See https://github.ibm.com/settings/tokens or https://github.ibm.com/settings/ssh
npm ERR! fatal: unable to access 'https://github.ibm.com/CognitiveAssetFactory/kpb-api-pkg/': The requested URL returned error: 403
npm ERR! 
npm ERR! exited with error code: 128
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-06-26T10_31_07_934Z-debug.log
```

On every push on master, travis CI is triggered, it downloads latest IBMCloud CLI (same as cf) version and execute a shell deploying script

.travis.yml
```
language: node_js
node_js:
  - '8'
script: echo "skipping tests"
before_deploy:
  - curl -L https://clis.ng.bluemix.net/download/bluemix-cli/latest/linux64 | tar -zx
  - chmod -R u+x ./Bluemix_CLI/bin
  - chmod +x ./deploy.sh
deploy:
  provider: script
  script: ./deploy.sh
  on:
    repo: CognitiveAssetFactory/kpb-singlenode-api
    branch: master
  skip_cleanup: true
```
The shell script loads Travis CI ENV vars to avoid exposing api key or tokens and to automate the IBMCloud login process and to trigger the equivalent of `cf push` which is `ibmcloud app push`

deploy.sh
```
#!/bin/bash

invocation_error=0

# - API_KEY: IBM Cloud API key
if [ -z ${API_KEY+x} ]; then echo 'Error: Environment variable API_KEY is undefined.'; invocation_error=1; fi
# - IBMCLOUD_ORGANIZATION: IBM Cloud/Cloud Foundry organization name
if [ -z ${IBMCLOUD_ORGANIZATION+x} ]; then echo 'Error: Environment variable IBMCLOUD_ORGANIZATION is undefined.'; invocation_error=1; fi
# - IBMCLOUD_SPACE: IBM Cloud/Cloud Foundry space name
if [ -z ${IBMCLOUD_SPACE+x} ]; then echo 'Error: Environment variable IBMCLOUD_SPACE is undefined.'; invocation_error=1; fi
# - API_ENDPOINT: IBM Cloud API endpoint (default to US-South region)
if [ -z ${API_ENDPOINT+x} ]; then export API_ENDPOINT='https://api.ng.bluemix.net'; fi

# Last check
if [ ${invocation_error} -eq 1 ]; then echo 'Something went wrong, check for previous errors.'; exit 1; fi

# Script
./Bluemix_CLI/bin/ibmcloud config --check-version false
./Bluemix_CLI/bin/ibmcloud api $API_ENDPOINT
./Bluemix_CLI/bin/ibmcloud login --apikey $API_KEY
./Bluemix_CLI/bin/ibmcloud target -o $IBMCLOUD_ORGANIZATION -s $IBMCLOUD_SPACE
./Bluemix_CLI/bin/ibmcloud app push kpb-singlenode-api 
```

The big problem is there is no way to define the context of `git` that cf agent should use for each git instructions... maybe in the `manifest.yml` ? 
But it might induce another problem which is I can't provide to Travis the manifest.yml?

```
applications:
- path: .
  memory: 1024M
  instances: 1
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  name: kpb-singlenode-api
  command: node build/server.js
  disk_quota: 1024M
```
so I'm stuck!
Thank you for helping, have a nice day!

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction
