### ISSUE TITLE
`pnpm` support

### ISSUE THREAD

**Issue by raulfdm** [cloudfoundry/nodejs-buildpack#398]
## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

- `PCF 2.11.8`
-  Cli version `6.53.0`

## What version of the buildpack you are using?

- `Nodejs Buildpack version 1.7.61`

## If you were attempting to accomplish a task, what was it you were attempting to do?

I'm trying to run the `nodejs_buildpack` with `pnpm` as installer.

## What did you expect to happen?

I can either specify an installation command (e.g. installCommand: `npm i -g pnpm && pnpm i --filter my-project`) or having `pnpm` available globally by default + identify I'm have `pnpm-lock.yaml`.

This would be nicer because I'm currently using pnpm workspaces and differently from `npm` or `yarn`, it allow me to install dependencies from a custom project, instead installing ALL dependencies from ALL projects. This will lead into a less deps to download, faster deployments and when I compact to send to our cloundfoundry server, a smaller `.tar.gz`.

## What was the actual behavior?

It does not find `yarn.lock` / `package-lock.json` and fallback to `npm install`.

## Can you provide a sample app?

Unfortunately I can't since this is a company's project. But summarizing:

- I have a created a project with pnpm as dep. manager and enable workspaces;
- put a project, like for example a nextjs app to server side render my app;
- create a pipeline (on Azure Devops) with the following description:

  ```yml
  # pipeline.yml
  # ...
  steps:
    - task: CloudFoundryCLI@0
    displayName: Deploy ROP Portal CMS
    inputs:
      cfEndpoint: "pcf-t02-we"
      org: "online-org"
      space: "<company-workspace>"
      cfCommand: "<company cf command"
      cfArguments: "deploy-test.yml"
  ```

  ```yaml
  # deploy-test.yml
  deployments:
  - name: <company-project-name>
    manifest-file: manifest-test.yml
    target-hosts:
      - <company-host>
    routes:
      - domain: <company-domain>
        hostnames:
          - <company-host>
  ```

  ```yaml
  # manifest-test.yml
  applications:
  - name: <company-project-name>
    instances: 1
    disk_quota: 2G
    memory: 1G
    command: pnpm run start --filter portal -p 8080
    buildpacks:
      - staticfile_buildpack
      - nodejs_buildpack

  ```

## Logs

Since I cannot share the logs due security policies, I can say that the only error I had was the following one:

```
╔═════════════════════════════════════════════════════════════╗
║                                                             ║
║   Use "pnpm install" for installation in this project.      ║
║                                                             ║
║   If you don't have pnpm, install it via "npm i -g pnpm".   ║
║   For more details, go to https://pnpm.js.org/              ║
║                                                             ║
╚═════════════════════════════════════════════════════════════╝
```

And that's because I've added (to ensure everyone works with the same manager), https://pnpm.io/only-allow-pnpm as preinstall npm hook.

## Please confirm where necessary

- [ ] I have included a log output
- [x] My log includes an error message
- [x] I have included steps for reproduction
