### ISSUE TITLE
Methods PUT and DELETE not allowed

### ISSUE THREAD

**Issue by jfsimon** [cloudfoundry/nodejs-buildpack#57]
Hello,

Not really sure this is the best place to post this issue I'm having with my node.js application, but I can't find any resource on this subject. My application is a HTTP API built with node.js and pushed on a Cloud Foundry server (Bluemix) using this buildpack.

When I send `GET` or `POST` requests everything is fine, but when I send `PUT` or `DELETE` requests I receive `405 Not Allowed` response.

**Here is my `manifest.yml`**:

```yml
applications:
- name: api
  buildpack: https://github.com/cloudfoundry/buildpack-nodejs.git
  env:
    NODE_MODULES_CACHE: false
```

**And this is the response body**:

```html
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

* Am I missing something?
* Is there a way to configure the `Nginx` server?

Thanks for reading!
